[tools]
act = "0.2.83"
ansible = "12.1.0"
claude-code = "2.0.56"
delta = "0.18.2"
flux2 = "2.7.3"
gh = "2.82.1"
go = "1.25.3"
gofumpt = "0.9.2"
golangci-lint = "2.5.0"
helm = "3.19.0"
kind = "0.30.0"
kubectl = "1.34.1"
nerdctl = "2.1.6"
node = "25.1.0"
pipx = "1.8.0"
python = "3.14.0"
rg = "15.1.0"
swag = "1.16.6"
uv = "0.9.14"
"ubi:ardge-labs/goodman" = "0.3.0"
grpcurl = "1.9.3"
