name: Build

on:
  push:
    branches:
      - develop
      - main
      - 'support/*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ardge-labs/github-workflows/.github/workflows/go-build.yml@v1
    with:
      go-version: '1.25.4'
    secrets:
      ARDGE_GITHUB_PAT: ${{ secrets.ARDGE_GITHUB_PAT }}
