name: Lint

on:
  push:
    branches:
      - develop
      - main
      - 'support/*'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: ardge-labs/github-workflows/.github/workflows/go-lint.yml@v1
    with:
      go-version: '1.25.4'
      golangci-lint-version: 'v2.6.2'
      timeout: '5m'
    secrets:
      ARDGE_GITHUB_PAT: ${{ secrets.ARDGE_GITHUB_PAT }}
